(()=>{const PE=globalThis.PixelEditor,U=PE.ui,M=PE.model,C=PE.commands,R=PE.renderer;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const common=(nodes,get)=>{if(!nodes.length)return null;const v=get(nodes[0]);return nodes.every(n=>eq(get(n),v))?v:null;};
const field=(id,label,value,{type='number',min='',max='',step='1',disabled=false,mixed=false,readonly=false}={})=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" ${mixed?'placeholder="—" class="mixed"':''} value="${mixed?'':esc(value)}" ${min!==''?`min="${min}"`:''} ${max!==''?`max="${max}"`:''} ${step?`step="${step}"`:''} ${disabled?'disabled':''} ${readonly?'readonly':''}></div>`;
const section=(title,body,id='')=>`<div class="property-section" ${id?`id="${id}"`:''}><h4>${title}</h4>${body}</div>`;
const select=(id,label,opts,value,{disabled=false,mixed=false}={})=>`<div class="field"><label for="${id}">${label}</label><select id="${id}" ${disabled?'disabled':''}>${mixed?'<option value="" selected>—</option>':''}${opts.map(([v,t])=>`<option value="${esc(v)}" ${!mixed&&String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></div>`;
class Properties{
 constructor(editor,el){this.editor=editor;this.el=el;}
 renderPage(page){const d=!!page.locked,mode=page.fill?.mode||'solid';let html=section('页面',`${field('propPageName','名称',page.name,{type:'text'})}<label class="check"><input id="propPageLocked" type="checkbox" ${page.locked?'checked':''}> 锁定页面</label>`)+section('背景',`${select('propFill','填充',[['solid','纯色'],['dither','抖动'],['pattern','图案']],mode,{disabled:d})}${mode==='solid'?select('propBgSolid','颜色',[[0,'白'],[1,'黑']],page.fill?.value?1:0,{disabled:d}):''}`);if(mode==='dither')html+=this.ditherFields([page],d);if(mode==='pattern')html+=this.patternFields([page],d);this.el.innerHTML=html;this.bindPage(page);this.renderPreviews([page]);}
 bindPage(page){const update=(patch,label='编辑页面')=>this.editor.exec(new C.UpdatePageCommand(page.id,patch,label));const name=this.el.querySelector('#propPageName');if(name)name.onchange=()=>update({name:name.value},'重命名页面');const lock=this.el.querySelector('#propPageLocked');if(lock)lock.onchange=()=>update({locked:lock.checked},lock.checked?'锁定页面':'解锁页面');if(page.locked)return;const fill=this.el.querySelector('#propFill');if(fill)fill.onchange=()=>update(p=>({fill:{...(p.fill||{}),mode:fill.value}}),'背景填充');const solid=this.el.querySelector('#propBgSolid');if(solid)solid.onchange=()=>update(p=>({fill:{...(p.fill||{}),mode:'solid',value:Number(solid.value)?1:0}}),'背景颜色');const dmap={propDitherType:['type',v=>v],propDitherDensity:['density',v=>Math.max(0,Math.min(100,Number(v)))],propDitherMatrix:['matrix',Number],propDitherAlign:['align',v=>v],propDitherOffsetX:['offsetX',v=>Math.round(Number(v))],propDitherOffsetY:['offsetY',v=>Math.round(Number(v))]};for(const [id,[k,f]] of Object.entries(dmap)){const e=this.el.querySelector('#'+id);if(e)e.onchange=()=>update(p=>({dither:{...(p.dither||M.defaultDither()),[k]:f(e.value)}}),'修改背景抖动');}const pmap={propPatternType:['type',v=>v],propPatternLineWidth:['lineWidth',v=>Math.max(1,Math.min(16,Math.round(Number(v))))],propPatternGap:['gap',v=>Math.max(0,Math.min(32,Math.round(Number(v))))],propPatternAlign:['align',v=>v],propPatternOffsetX:['offsetX',v=>Math.round(Number(v))],propPatternOffsetY:['offsetY',v=>Math.round(Number(v))]};for(const [id,[k,f]] of Object.entries(pmap)){const e=this.el.querySelector('#'+id);if(e)e.onchange=()=>update(p=>({pattern:{...(p.pattern||M.defaultPattern()),[k]:f(e.value)}}),'修改背景图案');}}
 render(){const page=this.editor.activePage(),ids=this.editor.state.selection.ids,nodes=ids.map(id=>M.nodeById(page,id)).filter(Boolean),tree=new M.TreeModel(page);if(this.editor.pageSelectedId===page.id&&!nodes.length){this.renderPage(page);return;}if(!nodes.length){this.el.innerHTML='<div class="muted">未选择图层</div>';return;}const allLocked=nodes.every(n=>tree.isEffectivelyLocked(n.id)),sameType=nodes.every(n=>n.type===nodes[0].type);let html=this.general(nodes,allLocked)+this.transform(nodes,allLocked);if(sameType)html+=this.typeFields(nodes,allLocked);else html+='<div class="muted">不同类型：仅显示通用、位置、可见与锁定属性</div>';this.el.innerHTML=html;this.bind(nodes,allLocked);this.renderPreviews(nodes);}
 general(nodes,locked){const name=common(nodes,n=>n.name),vis=common(nodes,n=>n.visible!==false),lock=common(nodes,n=>!!n.locked);return section('通用',`${field('propName','名称',name??'',{type:'text',disabled:locked||nodes.length!==1,mixed:name==null})}<label class="check"><input id="propVisible" type="checkbox" ${vis===true?'checked':''}> 可见${vis==null?'（混合）':''}</label><label class="check"><input id="propLocked" type="checkbox" ${lock===true?'checked':''}> 锁定${lock==null?'（混合）':''}</label>`);}
 bounds(nodes){const page=this.editor.activePage();return nodes.map(n=>R.FramebufferRenderer.visualBounds(n.id,{project:this.editor.state.project,pageId:page.id,assets:this.editor.state.assets}));}
 transform(nodes,locked){const bs=this.bounds(nodes),x=common(bs,b=>b.x),y=common(bs,b=>b.y),w=common(bs,b=>b.w),h=common(bs,b=>b.h),boxTypes=nodes.every(n=>['rectangle','circle','text','image'].includes(n.type)),aspect=boxTypes?common(nodes,n=>!!n.aspectLocked):null;return section('位置',`<div class="row">${field('propX','X',x??'',{disabled:locked,mixed:x==null})}${field('propY','Y',y??'',{disabled:locked,mixed:y==null})}</div>${boxTypes?`<div class="row">${field('propW','W',w??'',{min:1,max:400,disabled:locked,mixed:w==null})}${field('propH','H',h??'',{min:1,max:300,disabled:locked,mixed:h==null})}</div><label class="check"><input id="propAspect" type="checkbox" ${aspect===true?'checked':''} ${locked?'disabled':''}> 锁定比例${aspect==null?'（混合）':''}</label>`:''}`);}
 fillFields(nodes,locked,textOnly=false){const mode=common(nodes,n=>n.fill?.mode||'transparent'),opts=textOnly?[['solid','纯色'],['dither','抖动'],['pattern','图案']]:[['transparent','透明'],['solid','纯色'],['dither','抖动'],['pattern','图案']];let s=section('填充',select('propFill','填充',opts,mode,{disabled:locked,mixed:mode==null}));if(mode==='dither')s+=this.ditherFields(nodes,locked);if(mode==='pattern')s+=this.patternFields(nodes,locked);return s;}
 ditherFields(nodes,locked){const g=k=>common(nodes,n=>n.dither?.[k]);return section('抖动',`${select('propDitherType','类型',[['bayer','Bayer'],['blueNoise','Blue Noise'],['random','Random']],g('type'),{disabled:locked,mixed:g('type')==null})}${field('propDitherDensity','密度 %',g('density')??'',{min:0,max:100,disabled:locked,mixed:g('density')==null})}<div class="row">${select('propDitherMatrix','矩阵',[[2,'2×2'],[4,'4×4'],[8,'8×8']],g('matrix'),{disabled:locked,mixed:g('matrix')==null})}${select('propDitherAlign','对齐',[['global','全局'],['object','对象']],g('align'),{disabled:locked,mixed:g('align')==null})}</div><div class="row">${field('propDitherOffsetX','偏移 X',g('offsetX')??'',{disabled:locked,mixed:g('offsetX')==null})}${field('propDitherOffsetY','偏移 Y',g('offsetY')??'',{disabled:locked,mixed:g('offsetY')==null})}</div><div class="preview-wrap"><canvas class="pixel-preview" id="ditherPreview" width="8" height="8"></canvas><span class="muted">8×8 实际像素预览</span></div>`,'ditherModule');}
 patternFields(nodes,locked){const g=k=>common(nodes,n=>n.pattern?.[k]);return section('图案',`${select('propPatternType','类型',[['horizontal','横条纹'],['vertical','竖条纹'],['diagSlash','斜条纹 /'],['diagBackslash','斜条纹 \\'],['crosshatch','十字条纹'],['dots','点阵'],['checkerboard','棋盘格']],g('type'),{disabled:locked,mixed:g('type')==null})}<div class="row">${field('propPatternLineWidth','线宽',g('lineWidth')??'',{min:1,max:16,disabled:locked,mixed:g('lineWidth')==null})}${field('propPatternGap','间距',g('gap')??'',{min:0,max:32,disabled:locked,mixed:g('gap')==null})}</div>${select('propPatternAlign','对齐',[['global','全局'],['object','对象']],g('align'),{disabled:locked,mixed:g('align')==null})}<div class="row">${field('propPatternOffsetX','偏移 X',g('offsetX')??'',{disabled:locked,mixed:g('offsetX')==null})}${field('propPatternOffsetY','偏移 Y',g('offsetY')??'',{disabled:locked,mixed:g('offsetY')==null})}</div><div class="preview-wrap"><canvas class="pixel-preview" id="patternPreview" width="8" height="8"></canvas><span class="muted">8×8 实际像素预览</span></div>`,'patternModule');}
 typeFields(nodes,locked){const n=nodes[0],g=k=>common(nodes,x=>x[k]),d=locked;if(n.type==='line')return section('直线',`<div class="row">${field('propX1','X1',g('x1')??'',{disabled:d,mixed:g('x1')==null})}${field('propY1','Y1',g('y1')??'',{disabled:d,mixed:g('y1')==null})}</div><div class="row">${field('propX2','X2',g('x2')??'',{disabled:d,mixed:g('x2')==null})}${field('propY2','Y2',g('y2')??'',{disabled:d,mixed:g('y2')==null})}</div>${field('propLineWidth','线宽',g('lineWidth')??'',{min:0,max:100,disabled:d,mixed:g('lineWidth')==null})}`);if(n.type==='rectangle'){let out=section('圆角',`<div class="corner-grid"><div class="row">${field('propRTL','左上',g('rTL')??'',{min:0,max:200,disabled:d,mixed:g('rTL')==null})}${field('propRTR','右上',g('rTR')??'',{min:0,max:200,disabled:d,mixed:g('rTR')==null})}</div><div class="row">${field('propRBL','左下',g('rBL')??'',{min:0,max:200,disabled:d,mixed:g('rBL')==null})}${field('propRBR','右下',g('rBR')??'',{min:0,max:200,disabled:d,mixed:g('rBR')==null})}</div></div>`)+section('描边',field('propLineWidth','线宽',g('lineWidth')??'',{min:0,max:100,disabled:d,mixed:g('lineWidth')==null}));return out+this.fillFields(nodes,d);}
 if(n.type==='circle')return section('描边',field('propLineWidth','线宽',g('lineWidth')??'',{min:0,max:100,disabled:d,mixed:g('lineWidth')==null}))+this.fillFields(nodes,d);
 if(n.type==='polygon'){let out=section('多边形',`${nodes.length===1?`${field('propPointCount','顶点数量',n.points.length,{min:3,max:24,disabled:d})}<div id="polygonPointList">${n.points.map((p,i)=>`<div class="point-row"><span>P${i+1}</span>${field(`propPoint${i}X`,'X',p.x,{disabled:d})}${field(`propPoint${i}Y`,'Y',p.y,{disabled:d})}</div>`).join('')}</div>`:'<div class="muted">多选时隐藏顶点列表</div>'}${field('propLineWidth','线宽',g('lineWidth')??'',{min:0,max:100,disabled:d,mixed:g('lineWidth')==null})}`);return out+this.fillFields(nodes,d);}
 if(n.type==='text'){const ff=common(nodes,x=>x.fontFamily),meta=(this.editor.state.project.fonts||[]).find(f=>f.family===ff),fs=common(nodes,x=>x.fixedFontSize||x.fontSize),text=common(nodes,x=>x.text),ls=common(nodes,x=>x.letterSpacing),line=common(nodes,x=>x.lineSpacing),ah=common(nodes,x=>x.alignH),av=common(nodes,x=>x.alignV),wrap=common(nodes,x=>x.wrap!==false),bold=common(nodes,x=>!!x.bold),inv=common(nodes,x=>!!x.invert);let out=section('文字',`${nodes.length===1?`<div class="field"><label>内容</label><textarea id="propText" ${d?'disabled':''}>${esc(n.text)}</textarea></div>`:''}${select('propFont','字体',this.fontOptionsArray(),ff,{disabled:d,mixed:ff==null})}<button id="importFontBtn" type="button" ${d?'disabled':''}>导入字体（可多选）</button><div class="row">${field('propFontSize','字号',fs??'',{min:1,max:200,disabled:d||!!meta?.fixedSize,mixed:fs==null})}${field('propLetterSpacing','字距',ls??'',{min:-20,max:100,disabled:d,mixed:ls==null})}</div>${field('propLineSpacing','行距',line??'',{min:-20,max:200,disabled:d,mixed:line==null})}<div class="row">${select('propAlignH','水平对齐',[['left','左'],['center','中'],['right','右']],ah,{disabled:d,mixed:ah==null})}${select('propAlignV','垂直对齐',[['top','上'],['middle','中'],['bottom','下']],av,{disabled:d,mixed:av==null})}</div><label class="check"><input id="propWrap" type="checkbox" ${wrap===true?'checked':''} ${d?'disabled':''}> 自动换行${wrap==null?'（混合）':''}</label><label class="check"><input id="propBold" type="checkbox" ${bold===true?'checked':''} ${d?'disabled':''}> 粗体${bold==null?'（混合）':''}</label><label class="check"><input id="propInvert" type="checkbox" ${inv===true?'checked':''} ${d?'disabled':''}> 黑底白字${inv==null?'（混合）':''}</label>`);return out+this.fillFields(nodes,d,true);}
 if(n.type==='image'&&nodes.length===1){const im=n.image||{};return section('图片',`${field('propImageFile','文件',n.sourceName||n.name,{type:'text',readonly:true,disabled:d})}<button id="replaceImageBtn" type="button" ${d?'disabled':''}>替换图片</button><div class="row">${select('propImageFit','适应方式',[['original','原始'],['contain','包含'],['cover','覆盖'],['stretch','拉伸']],im.fit,{disabled:d})}${select('propInterpolation','插值',[['nearest','最近邻'],['bilinear','双线性']],im.interpolation,{disabled:d})}</div><h4>裁剪</h4><div class="row">${field('propCropX','X',im.cropX,{min:0,max:n.sourceWidth-1,disabled:d})}${field('propCropY','Y',im.cropY,{min:0,max:n.sourceHeight-1,disabled:d})}</div><div class="row">${field('propCropW','W',im.cropW,{min:1,max:n.sourceWidth,disabled:d})}${field('propCropH','H',im.cropH,{min:1,max:n.sourceHeight,disabled:d})}</div>${select('propBwMode','黑白模式',[['threshold','阈值'],['dither','抖动']],im.bwMode,{disabled:d})}${im.bwMode==='threshold'?field('propThreshold','阈值',im.threshold,{min:0,max:255,disabled:d}):`${select('propImageDitherAlgorithm','算法',[['bayer','Bayer'],['blueNoise','Blue Noise'],['floydSteinberg','Floyd-Steinberg'],['atkinson','Atkinson']],im.ditherAlgorithm,{disabled:d})}${['bayer'].includes(im.ditherAlgorithm)?select('propImageBayerMatrix','Bayer 矩阵',[[2,'2×2'],[4,'4×4'],[8,'8×8']],im.bayerMatrix,{disabled:d}):''}<div class="preview-wrap"><canvas id="imageDitherPreview" class="image-preview" width="64" height="48"></canvas></div>`}<label class="check"><input id="propImageInvert" type="checkbox" ${im.invert?'checked':''} ${d?'disabled':''}>反相</label>`);}
 return'';}
 fontOptionsArray(){const built=[['sans-serif','系统默认中文'],['Microsoft YaHei, sans-serif','微软雅黑'],['PingFang SC, sans-serif','苹方'],['Noto Sans CJK SC, Source Han Sans SC, sans-serif','思源黑体 / Noto'],['WenQuanYi Micro Hei, sans-serif','文泉驿微米黑'],['SimHei, sans-serif','黑体'],['SimSun, serif','宋体'],['KaiTi, serif','楷体'],['FangSong, serif','仿宋'],['Noto Sans Mono CJK SC, monospace','等宽中文']];return [...built,...((this.editor.state.project.fonts||[]).map(f=>[f.family,f.name||f.family]))];}
 bind(nodes,locked){const page=this.editor.activePage(),ids=nodes.map(n=>n.id),all=(patch,label='编辑属性')=>this.editor.exec(new C.UpdateNodesCommand(ids,patch,page.id,label)),one=nodes.length===1?nodes[0]:null,listen=(id,event,fn)=>{const el=this.el.querySelector('#'+id);if(el)el.addEventListener(event,()=>fn(el));};
 const vis=this.el.querySelector('#propVisible');if(vis){const v=common(nodes,n=>n.visible!==false);vis.indeterminate=v==null;vis.onchange=e=>this.editor.exec(new C.SetVisibilityCommand(ids,e.target.checked,page.id));}const lock=this.el.querySelector('#propLocked');if(lock){const v=common(nodes,n=>!!n.locked);lock.indeterminate=v==null;lock.onchange=e=>this.editor.exec(new C.ToggleLockCommand(ids,e.target.checked,page.id));}if(locked)return;
 const name=this.el.querySelector('#propName');if(name&&nodes.length===1)name.addEventListener('change',e=>all({name:e.target.value},'重命名图层'));
 ['X','Y'].forEach(axis=>{const el=this.el.querySelector('#prop'+axis);if(!el)return;const commit=()=>{if(el.value==='')return;const v=Number(el.value);if(Number.isFinite(v))this.editor.setSelectionAxis(axis.toLowerCase(),Math.round(v));};el.addEventListener('change',commit);el.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();commit();}});});
 const box=nodes.every(n=>['rectangle','circle','text','image'].includes(n.type));if(box){listen('propW','change',el=>this.editor.setSelectionSize('w',Math.max(1,Math.round(Number(el.value)))));listen('propH','change',el=>this.editor.setSelectionSize('h',Math.max(1,Math.round(Number(el.value)))));listen('propAspect','change',el=>all({aspectLocked:el.checked},'锁定比例'));}
 const numeric=(id,key,min=-Infinity,max=Infinity,label='编辑属性')=>listen(id,'change',el=>all({[key]:Math.max(min,Math.min(max,Math.round(Number(el.value))))},label));numeric('propLineWidth','lineWidth',0,100,'线宽');
 if(one?.type==='line'){for(const [id,key] of [['propX1','x1'],['propY1','y1'],['propX2','x2'],['propY2','y2']])numeric(id,key,-9999,9999,'修改直线');}
 if(nodes[0].type==='rectangle')for(const [id,key] of [['propRTL','rTL'],['propRTR','rTR'],['propRBL','rBL'],['propRBR','rBR']])numeric(id,key,0,200,'修改圆角');
 const fill=this.el.querySelector('#propFill');if(fill)fill.onchange=e=>all(n=>({fill:{...(n.fill||{}),mode:e.target.value}}),'填充');const bgSolid=this.el.querySelector('#propBgSolid');if(bgSolid)bgSolid.onchange=e=>all(n=>({fill:{...(n.fill||{}),mode:'solid',value:Number(e.target.value)?1:0}}),'背景颜色');
 this.bindDither(nodes);this.bindPattern(nodes);
 if(one?.type==='polygon'){listen('propPointCount','change',el=>this.editor.setPolygonPointCount(one.id,el.value));one.points.forEach((p,i)=>{listen(`propPoint${i}X`,'change',el=>{const pts=one.points.map(q=>({...q}));pts[i].x=Math.round(Number(el.value));this.editor.exec(new C.UpdateNodesCommand([one.id],{points:pts},page.id,'修改顶点'));});listen(`propPoint${i}Y`,'change',el=>{const pts=one.points.map(q=>({...q}));pts[i].y=Math.round(Number(el.value));this.editor.exec(new C.UpdateNodesCommand([one.id],{points:pts},page.id,'修改顶点'));});});}
 if(nodes[0].type==='text')this.bindText(nodes);
 if(one?.type==='image')this.bindImage(one);
 }
 bindDither(nodes){const ids=nodes.map(n=>n.id),page=this.editor.activePage(),patch=(key,value)=>this.editor.exec(new C.UpdateNodesCommand(ids,n=>({dither:{...(n.dither||M.defaultDither()),[key]:value}}),page.id,'修改抖动'));const map={propDitherType:['type',v=>v],propDitherDensity:['density',v=>Math.max(0,Math.min(100,Number(v)))],propDitherMatrix:['matrix',Number],propDitherAlign:['align',v=>v],propDitherOffsetX:['offsetX',v=>Math.round(Number(v))],propDitherOffsetY:['offsetY',v=>Math.round(Number(v))]};for(const [id,[k,f]] of Object.entries(map)){const e=this.el.querySelector('#'+id);if(e)e.onchange=()=>patch(k,f(e.value));}}
 bindPattern(nodes){const ids=nodes.map(n=>n.id),page=this.editor.activePage(),patch=(key,value)=>this.editor.exec(new C.UpdateNodesCommand(ids,n=>({pattern:{...(n.pattern||M.defaultPattern()),[key]:value}}),page.id,'修改图案'));const map={propPatternType:['type',v=>v],propPatternLineWidth:['lineWidth',v=>Math.max(1,Math.min(16,Math.round(Number(v))))],propPatternGap:['gap',v=>Math.max(0,Math.min(32,Math.round(Number(v))))],propPatternAlign:['align',v=>v],propPatternOffsetX:['offsetX',v=>Math.round(Number(v))],propPatternOffsetY:['offsetY',v=>Math.round(Number(v))]};for(const [id,[k,f]] of Object.entries(map)){const e=this.el.querySelector('#'+id);if(e)e.onchange=()=>patch(k,f(e.value));}}
 bindText(nodes){const page=this.editor.activePage(),ids=nodes.map(n=>n.id),all=(patch,label)=>this.editor.exec(new C.UpdateNodesCommand(ids,patch,page.id,label)),one=nodes.length===1?nodes[0]:null,text=this.el.querySelector('#propText');if(text&&one){let composing=false;text.addEventListener('compositionstart',()=>composing=true);text.addEventListener('compositionend',e=>{composing=false;all({text:e.target.value},'文字');});text.addEventListener('change',e=>{if(!composing)all({text:e.target.value},'文字');});}const font=this.el.querySelector('#propFont');if(font)font.onchange=()=>{const rec=(this.editor.state.project.fonts||[]).find(f=>f.family===font.value);all(n=>({fontFamily:font.value,fixedFontSize:rec?.fixedSize||null,fontSize:rec?.fixedSize||n.fontSize}),'字体');};const num=(id,key,min,max)=>{const e=this.el.querySelector('#'+id);if(e)e.onchange=()=>all({[key]:Math.max(min,Math.min(max,Math.round(Number(e.value))))},'文字排版');};num('propFontSize','fontSize',1,200);num('propLetterSpacing','letterSpacing',-20,100);num('propLineSpacing','lineSpacing',-20,200);for(const [id,key] of [['propAlignH','alignH'],['propAlignV','alignV']]){const e=this.el.querySelector('#'+id);if(e)e.onchange=()=>all({[key]:e.value},'文字排版');}for(const [id,key] of [['propWrap','wrap'],['propBold','bold'],['propInvert','invert']]){const e=this.el.querySelector('#'+id);if(e)e.onchange=()=>all({[key]:e.checked},'文字排版');}this.el.querySelector('#importFontBtn')?.addEventListener('click',()=>document.querySelector('#fileFont')?.click());}
 bindImage(n){const page=this.editor.activePage(),id=n.id,update=(fn,label)=>this.editor.exec(new C.UpdateNodesCommand([id],x=>({image:fn({...x.image})}),page.id,label));this.el.querySelector('#replaceImageBtn')?.addEventListener('click',()=>this.editor.chooseReplacementImage(id));for(const [eid,key] of [['propImageFit','fit'],['propInterpolation','interpolation'],['propBwMode','bwMode'],['propImageDitherAlgorithm','ditherAlgorithm']]){const e=this.el.querySelector('#'+eid);if(e)e.onchange=()=>update(im=>(im[key]=e.value,im),'图片属性');}for(const [eid,key,min,max] of [['propCropX','cropX',0,n.sourceWidth-1],['propCropY','cropY',0,n.sourceHeight-1],['propCropW','cropW',1,n.sourceWidth],['propCropH','cropH',1,n.sourceHeight],['propThreshold','threshold',0,255],['propImageBayerMatrix','bayerMatrix',2,8]]){const e=this.el.querySelector('#'+eid);if(e)e.onchange=()=>update(im=>(im[key]=Math.max(min,Math.min(max,Math.round(Number(e.value)))),im),'图片属性');}const inv=this.el.querySelector('#propImageInvert');if(inv)inv.onchange=()=>update(im=>(im.invert=inv.checked,im),'图片反相');}
 renderPreviews(nodes){if(nodes.length!==1)return;const n=nodes[0],draw=(id,pixel)=>{const c=this.el.querySelector('#'+id);if(!c)return;const x=c.getContext('2d',{alpha:false}),im=x.createImageData(c.width,c.height);for(let y=0;y<c.height;y++)for(let xx=0;xx<c.width;xx++){const black=pixel(xx,y),v=black?0:255,i=(y*c.width+xx)*4;im.data[i]=im.data[i+1]=im.data[i+2]=v;im.data[i+3]=255;}x.putImageData(im,0,0);};draw('ditherPreview',(x,y)=>R.graphicDitherPixel(n.dither,x,y,x,y));draw('patternPreview',(x,y)=>R.patternPixel(n.pattern,x,y,x,y));const c=this.el.querySelector('#imageDitherPreview');if(c&&n.type==='image'){const rr=R.ImageRenderer.render(n,this.editor.state.assets);if(rr){const bin=R.ditherImageData(rr.data,n.w,n.h,{algorithm:n.image?.ditherAlgorithm||'bayer',bayerMatrix:n.image?.bayerMatrix||4,invert:!!n.image?.invert}),tmp=document.createElement('canvas');tmp.width=n.w;tmp.height=n.h;const tx=tmp.getContext('2d'),im=tx.createImageData(n.w,n.h);for(let i=0;i<bin.length;i++){const v=bin[i]?0:255,j=i*4;im.data[j]=im.data[j+1]=im.data[j+2]=v;im.data[j+3]=255;}tx.putImageData(im,0,0);const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(tmp,0,0,c.width,c.height);}}}
}
U.Properties=Properties;})();
