import { normalizeTransform } from '../transforms/transform-model.js';
import { TreeModel } from './tree-model.js';

const BOX_TYPES = new Set(['rectangle','circle','text','image','raster']);
function finiteInteger(value,fallback=0){const number=Number(value);return Number.isFinite(number)?Math.round(number):Math.round(Number(fallback)||0);}
function nearestEvenInteger(value,fallback=0){const number=Number(value);if(!Number.isFinite(number))return nearestEvenInteger(fallback,0);const lower=Math.floor(number),fraction=number-lower;if(Math.abs(fraction-0.5)<1e-9)return Math.abs(lower%2)===0?lower:lower+1;return Math.round(number);}
function positiveInteger(value,fallback=1){return Math.max(1,finiteInteger(value,fallback));}
function integerPoint(point,fallback={x:0,y:0}){return{x:finiteInteger(point?.x,fallback?.x),y:finiteInteger(point?.y,fallback?.y)};}
function normalizeCommittedTransform(value={}){const output=normalizeTransform(value);for(const key of ['translateX','translateY']){if(!Object.hasOwn(output,key))continue;const integer=finiteInteger(output[key]);if(integer===0)delete output[key];else output[key]=integer;}return output;}
function normalizeNodeGeometry(node){if(!node||typeof node!=='object')return node;if(BOX_TYPES.has(node.type)){node.x=finiteInteger(node.x);node.y=finiteInteger(node.y);node.w=positiveInteger(node.w);node.h=positiveInteger(node.h);}else if(node.type==='line'){node.x1=finiteInteger(node.x1);node.y1=finiteInteger(node.y1);node.x2=finiteInteger(node.x2);node.y2=finiteInteger(node.y2);}else if(node.type==='polygon')node.points=(node.points||[]).map(point=>integerPoint(point));if(node.transform&&typeof node.transform==='object')node.transform=normalizeCommittedTransform(node.transform);return node;}
function normalizeGeometryPatch(node,patch){if(!patch||typeof patch!=='object')return patch;const output=structuredClone(patch);if(BOX_TYPES.has(node?.type)){if(Object.hasOwn(output,'x'))output.x=finiteInteger(output.x,node.x);if(Object.hasOwn(output,'y'))output.y=finiteInteger(output.y,node.y);if(Object.hasOwn(output,'w'))output.w=positiveInteger(output.w,node.w);if(Object.hasOwn(output,'h'))output.h=positiveInteger(output.h,node.h);}else if(node?.type==='line'){for(const key of ['x1','y1','x2','y2'])if(Object.hasOwn(output,key))output[key]=finiteInteger(output[key],node[key]);}else if(node?.type==='polygon'&&Object.hasOwn(output,'points'))output.points=(output.points||[]).map((point,index)=>integerPoint(point,node.points?.[index]));if(Object.hasOwn(output,'transform'))output.transform=normalizeCommittedTransform(output.transform);return output;}
function normalizeCommittedProject(project){for(const page of project?.pages||[])for(const node of page.nodes||[])normalizeNodeGeometry(node);return project;}
function invariantViolations(project){const violations=[];const checkInteger=(node,path,value)=>{if(!Number.isInteger(value))violations.push(`${node.type}:${node.id||'?'}:${path}=${value}`);};for(const page of project?.pages||[]){for(const node of page.nodes||[]){if(BOX_TYPES.has(node.type)){checkInteger(node,'x',node.x);checkInteger(node,'y',node.y);checkInteger(node,'w',node.w);checkInteger(node,'h',node.h);if(node.w<1||node.h<1)violations.push(`${node.type}:${node.id||'?'}:size=${node.w}x${node.h}`);}else if(node.type==='line'){for(const key of ['x1','y1','x2','y2'])checkInteger(node,key,node[key]);}else if(node.type==='polygon')(node.points||[]).forEach((point,index)=>{checkInteger(node,`points[${index}].x`,point.x);checkInteger(node,`points[${index}].y`,point.y);});const canonical=normalizeCommittedTransform(node.transform||{});if(JSON.stringify(canonical)!==JSON.stringify(node.transform||{}))violations.push(`${node.type}:${node.id||'?'}:transform`);}try{new TreeModel(page).validateHierarchy();}catch(error){violations.push(`page:${page.id}:hierarchy:${error?.message||error}`);}}return violations;}
function assertProjectInvariants(project){const violations=invariantViolations(project);if(violations.length)throw new Error(`元素位置、尺寸与 transform 平移必须为整数像素，且 V17 模型必须有效：${violations.slice(0,8).join(', ')}`);return project;}

export{BOX_TYPES,finiteInteger,nearestEvenInteger,positiveInteger,integerPoint,normalizeCommittedTransform,normalizeNodeGeometry,normalizeGeometryPatch,normalizeCommittedProject,invariantViolations,assertProjectInvariants};
