import { normalizeCommittedProject, assertProjectInvariants } from '../model/invariants.js';
import { EditSession, mergeDescriptorKey, resolveMergeDescriptor } from './edit-session.js';

const cloneProject = value => structuredClone(value);

class CommandBus {
  constructor(state, { limit = 100 } = {}) { this.state=state;this.limit=limit;this.entries=[];this.cursor=0;this.session=null;this._pendingPropertyChannel='';this._mergeChainKey=null;this._mergeChainCursor=null;this._mergeBreakReason='';this._normalizeAndValidate();this.entries=[{label:'初始状态',snapshot:cloneProject(state.project)}];state.selection?.setBoundaryHandler?.(reason=>this.breakMergeChain(reason)); }
  _normalizeAndValidate(){normalizeCommittedProject(this.state.project);assertProjectInvariants(this.state.project);return this.state.project;}
  _clearMerge(reason=''){this._mergeChainKey=null;this._mergeChainCursor=null;this._mergeBreakReason=String(reason||'');}
  _trim(){while(this.entries.length>this.limit+1){this.entries.shift();this.cursor-=1;}}
  _push(label,snapshot,descriptor=null){if(this.cursor<this.entries.length-1)this.entries.splice(this.cursor+1);const key=mergeDescriptorKey(descriptor)||'';this.entries.push({label:label||'编辑',snapshot,mergeDescriptor:descriptor||null,mergeDescriptorKey:key||null});this.cursor=this.entries.length-1;this._trim();this.state.dirty=true;return true;}
  _record(command,after){const descriptor=resolveMergeDescriptor(command)||null,key=mergeDescriptorKey(descriptor)||'';const canMerge=Boolean(key)&&this._mergeChainKey===key&&this._mergeChainCursor===this.cursor&&this.cursor>0&&this.cursor===this.entries.length-1&&this.entries[this.cursor]?.mergeDescriptorKey===key;if(canMerge){const entry=this.entries[this.cursor];entry.snapshot=after;entry.label=command.label||entry.label;entry.mergeDescriptor=descriptor;entry.mergeDescriptorKey=key;this.state.dirty=true;return true;}this._push(command.label||'编辑',after,descriptor);if(key){this._mergeChainKey=key;this._mergeChainCursor=this.cursor;this._mergeBreakReason='';}else this._clearMerge('nonmergeable-command');return true;}
  execute(command){if(!command||typeof command.execute!=='function')throw new Error('invalid command');if(this._pendingPropertyChannel&&!this.session){const inferred=resolveMergeDescriptor(command)||{};this.beginSession({operation:inferred.operation||'property',targets:inferred.targets||[],channel:this._pendingPropertyChannel,label:command.label||'编辑属性'});this._pendingPropertyChannel='';}if(this.session)return this.updateSession(command);const changed=command.execute(this.state);if(changed===false)return false;this._normalizeAndValidate();return this._record(command,cloneProject(this.state.project));}
  beginSession(descriptor={}){if(this.session)this.commitSession();this._clearMerge('session-start');this.session=new EditSession(this,descriptor);return this.session;}
  updateSession(command){if(!command||typeof command.execute!=='function')throw new Error('invalid command');if(!this.session)this.beginSession(resolveMergeDescriptor(command)||{label:command.label||'编辑'});const session=this.session,changed=command.execute(this.state);if(changed===false)return false;this._normalizeAndValidate();const snapshot=cloneProject(this.state.project);session.update(command,snapshot);if(session.entryIndex==null){this._push(session.label||'编辑',snapshot,session.descriptor);session.entryIndex=this.cursor;}else{const entry=this.entries[session.entryIndex];if(entry){entry.snapshot=snapshot;entry.label=session.label||entry.label;entry.mergeDescriptor=session.descriptor||null;entry.mergeDescriptorKey=mergeDescriptorKey(session.descriptor)||null;}}this.state.dirty=true;this._clearMerge('session-preview');return true;}
  commitSession(){const session=this.session;if(!session)return false;this.session=null;this._pendingPropertyChannel='';if(!session.changed){this._clearMerge('session-empty');return false;}this._normalizeAndValidate();const snapshot=cloneProject(this.state.project);if(JSON.stringify(snapshot)===JSON.stringify(session.startSnapshot)){this.entries=cloneProject(session.startEntries);this.cursor=session.startCursor;this.state.dirty=session.startDirty;this._clearMerge('session-noop');return false;}const entry=session.entryIndex==null?null:this.entries[session.entryIndex];if(entry){entry.snapshot=snapshot;entry.label=session.label||entry.label;entry.mergeDescriptor=session.descriptor||null;entry.mergeDescriptorKey=mergeDescriptorKey(session.descriptor)||null;}else this._push(session.label||'编辑',snapshot,session.descriptor);this._clearMerge('session-commit');return true;}
  cancelSession(){const session=this.session;if(!session)return false;this.session=null;this._pendingPropertyChannel='';this.state.project=cloneProject(session.startSnapshot);this.entries=cloneProject(session.startEntries);this.cursor=session.startCursor;this.state.dirty=session.startDirty;this._clearMerge('session-cancel');return true;}
  breakMergeChain(reason=''){const text=String(reason||'');if(text.startsWith('property-start:')){if(this.session)this.commitSession();this._pendingPropertyChannel=text.slice('property-start:'.length)||'property';this._clearMerge(text);return;}if(this.session)this.commitSession();this._pendingPropertyChannel='';this._clearMerge(text);}
  restore(index){if(index<0||index>=this.entries.length)return false;this.state.project=cloneProject(this.entries[index].snapshot);this._normalizeAndValidate();this.cursor=index;this.state.dirty=true;return true;}
  undo(){if(this.session)this.commitSession();this._clearMerge('undo');return this.cursor>0?this.restore(this.cursor-1):false;}
  redo(){if(this.session)this.commitSession();this._clearMerge('redo');return this.cursor<this.entries.length-1?this.restore(this.cursor+1):false;}
  jump(index){if(this.session)this.commitSession();this._clearMerge('jump');return this.restore(index);}
  reset(project=this.state.project,label='初始状态'){if(this.session)this.cancelSession();this.state.project=project;this._normalizeAndValidate();this.entries=[{label,snapshot:cloneProject(this.state.project)}];this.cursor=0;this._pendingPropertyChannel='';this._clearMerge('reset');this.state.selection?.setBoundaryHandler?.(reason=>this.breakMergeChain(reason));}
}

export { CommandBus, cloneProject };
