(()=>{
const PE=globalThis.PixelEditor,M=PE.model,C=PE.commands,R=PE.renderer,I=PE.interaction,P=PE.persistence,U=PE.ui;
const ZOOMS=[1,2,3,4,5,6,7,8,10,12,14,16,18,20,22,24,26,28,30];
const $=s=>document.querySelector(s);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function dataUrlFromFile(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(file);});}
function decodeImage(dataUrl,targetW=null,targetH=null){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=Math.max(1,Math.round(targetW||im.naturalWidth||im.width));c.height=Math.max(1,Math.round(targetH||im.naturalHeight||im.height));const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0,c.width,c.height);res({width:c.width,height:c.height,data:x.getImageData(0,0,c.width,c.height).data});};im.onerror=rej;im.src=dataUrl;});}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},0);}
function inferFixedFontSize(name){const m=String(name||'').match(/(?:^|[_\s-])(\d{1,3})px(?:[_\s.-]|$)/i);return m?Number(m[1]):null;}
function parseSvgMeta(text){const vb=String(text).match(/viewBox\s*=\s*["']([^"']+)["']/i),nums=vb?vb[1].trim().split(/[\s,]+/).map(Number):null,wAttr=String(text).match(/\bwidth\s*=\s*["']([0-9.]+)/i),hAttr=String(text).match(/\bheight\s*=\s*["']([0-9.]+)/i);let w=nums&&nums.length===4&&nums.every(Number.isFinite)?Math.abs(nums[2]):Number(wAttr?.[1]),h=nums&&nums.length===4&&nums.every(Number.isFinite)?Math.abs(nums[3]):Number(hAttr?.[1]);if(!Number.isFinite(w)||w<=0)w=300;if(!Number.isFinite(h)||h<=0)h=150;return{viewBox:nums&&nums.length===4?nums:null,width:Math.max(1,Math.round(w)),height:Math.max(1,Math.round(h))};}
function parseXbmText(text){const wm=text.match(/#define\s+\w+_width\s+(\d+)/),hm=text.match(/#define\s+\w+_height\s+(\d+)/),bm=text.match(/\{([\s\S]*?)\}/);if(!wm||!hm||!bm)throw new Error('Invalid XBM');const width=Number(wm[1]),height=Number(hm[1]),bytes=(bm[1].match(/0x[0-9a-fA-F]+|\d+/g)||[]).map(Number),rowBytes=Math.ceil(width/8),pixels=new Uint8Array(width*height);if(bytes.length<rowBytes*height)throw new Error('Invalid XBM data');for(let y=0;y<height;y++)for(let x=0;x<width;x++)pixels[y*width+x]=(bytes[y*rowBytes+Math.floor(x/8)]>>(x%8))&1;return{width,height,pixels};}
function xbmToCanvas(xbm){const c=document.createElement('canvas');c.width=xbm.width;c.height=xbm.height;const x=c.getContext('2d'),im=x.createImageData(c.width,c.height);for(let i=0;i<xbm.pixels.length;i++){const v=xbm.pixels[i]?0:255,j=i*4;im.data[j]=im.data[j+1]=im.data[j+2]=v;im.data[j+3]=255;}x.putImageData(im,0,0);return c;}
class Workspace{
 constructor(){this.state={project:M.createProject(),assets:new M.AssetStore(),selection:new M.SelectionSet(),dirty:false,projectFileHandle:null,projectFileName:''};this.pageSelectedId=this.state.project.activePageId;this.bus=new C.CommandBus(this.state,{limit:100});this.files=new P.ProjectFiles(this.state);this.autosave=new P.Autosave(this.state);this.clipboard=new I.Clipboard();this.zoom=1;this.tool='pointer';this.overlayState={};this.customGesture=null;this.spaceDown=false;this.treeDragId=null;this.fontFaceCache=new Map();this.lastFramebuffer=new Uint8Array(120000);}
 mount(){this.canvas=$('#screenCanvas');this.overlay=$('#overlaySvg');this.ctx=this.canvas.getContext('2d',{alpha:false});this.pageLayers=new U.PageDock(this,$('#pageLayerDock'));this.properties=new U.Properties(this,$('#properties'));this.history=new U.HistoryDock(this,$('#historyDock'));this.toolbar=new U.Toolbar(this);this.toolbar.mount();this.setupTopbar();this.setupCanvas();this.setupKeyboard();this.setupFiles();this.setupDockSplitters();this.setupRulers();this.setupContextMenu();this.tryRestoreAutosave();this.applyLayout();this.applyZoom();this.renderAll();this.autosaveTimer=setInterval(()=>this.autosave.run(),300000);window.addEventListener('beforeunload',e=>{if(this.state.dirty){e.preventDefault();e.returnValue='';}});globalThis.PixelEditorTest=this.testApi();return this;}
 activePage(){return M.pageById(this.state.project,this.state.project.activePageId);}
 activePageId(){return this.state.project.activePageId;}
 exec(cmd){const before=this.state.project.activePageId,ok=this.bus.execute(cmd);if(ok){if(this.state.project.activePageId!==before)this.pageSelectedId=this.state.project.activePageId;this.renderAll();}return ok;}
 setActivePage(id){return this.selectPage(id);} selectPage(id){if(!M.pageById(this.state.project,id))return false;this.state.project.activePageId=id;this.state.selection.clear();this.pageSelectedId=id;this.overlayState={};this.renderAll();return true;}
 setTool(tool){if(!['pointer','select','pencil','eraser','line','rectangle','circle','polygon','image','text'].includes(tool))return;this.cancelCustomGesture();this.tool=tool;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));if(tool==='image'){$('#fileImage').click();this.tool='pointer';document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool==='pointer'));}this.updateInteraction();}
 setupTopbar(){const zs=$('#zoomSelect');zs.innerHTML=ZOOMS.map(z=>`<option value="${z}">${z*100}%</option>`).join('');zs.value=String(this.zoom);zs.onchange=()=>this.setZoom(Number(zs.value));$('#undoBtn').onclick=()=>{if(this.bus.undo()){this.state.selection.clear();this.renderAll();}};$('#redoBtn').onclick=()=>{if(this.bus.redo()){this.state.selection.clear();this.renderAll();}};$('#newBtn').onclick=()=>this.newProject();$('#saveBtn').onclick=()=>this.saveProject();$('#openBtn').onclick=()=>this.openProject();$('#exportPngBtn').onclick=()=>this.exportPng();}
 newProject({force=false}={}){if(!force&&this.state.dirty&&typeof confirm==='function'&&!confirm('当前工程有未保存修改，确认新建并丢弃这些修改吗？'))return false;this.autosave?.clear();this.state.project=M.createProject();this.state.assets=new M.AssetStore();this.state.selection.clear();this.pageSelectedId=this.state.project.activePageId;this.state.projectFileHandle=null;this.state.projectFileName='';this.state.dirty=false;this.bus=new C.CommandBus(this.state,{limit:100});this.files=new P.ProjectFiles(this.state);this.autosave=new P.Autosave(this.state);this.clipboard=new I.Clipboard();this.applyLayout();this.renderAll();return true;}
 tryRestoreAutosave(){const out=this.autosave?.read?.();if(!out)return false;let restore=true;if(typeof confirm==='function')restore=confirm('检测到自动保存的工程，是否恢复？');if(!restore){this.autosave.clear();return false;}this.state.project=out.project;this.state.assets=out.assets;this.state.selection.clear();this.pageSelectedId=this.state.project.activePageId;this.state.projectFileHandle=null;this.state.projectFileName='';this.state.dirty=true;this.bus=new C.CommandBus(this.state,{limit:100});return true;}
 setZoom(z){if(!ZOOMS.includes(z))return;this.zoom=z;$('#zoomSelect').value=String(z);this.applyZoom();this.renderRulers();this.renderOverlay();}
 applyZoom(){const w=400*this.zoom,h=300*this.zoom;for(const c of [this.canvas,this.overlay]){c.style.width=w+'px';c.style.height=h+'px';}$('#stage').style.width=w+'px';$('#stage').style.height=h+'px';const grid=this.zoom>=8;this.overlay.classList.toggle('pixel-grid',grid);this.overlay.style.backgroundImage=grid?'linear-gradient(to right, rgba(110,110,110,.34) 1px, transparent 1px),linear-gradient(to bottom, rgba(110,110,110,.34) 1px, transparent 1px)':'none';this.overlay.style.backgroundSize=grid?`${this.zoom}px ${this.zoom}px`:'';this.overlay.style.backgroundPosition='0 0';$('#topRuler').style.width='';$('#leftRuler').style.height='';}
 logicalPoint(e){const b=this.canvas.getBoundingClientRect();return{x:clamp(Math.floor((e.clientX-b.left)*400/Math.max(1,b.width)),0,399),y:clamp(Math.floor((e.clientY-b.top)*300/Math.max(1,b.height)),0,299)};} logicalPointFloat(e){const b=this.canvas.getBoundingClientRect();return{x:clamp((e.clientX-b.left)*400/Math.max(1,b.width),0,400),y:clamp((e.clientY-b.top)*300/Math.max(1,b.height),0,300)};}
 updateInteraction(){const page=this.activePage();if(!page)return;this.state.pageSelectedId=this.pageSelectedId;const hit=new I.HitTest(this.state.project,page.id,this.state.assets),snap=new I.SnapEngine(this.state.project,page.id,this.state.assets);this.interaction=new I.InteractionController({state:this.state,bus:this.bus,hitTest:hit,snapEngine:snap,getZoom:()=>this.zoom,modeKind:this.tool==='select'?'marquee':'pointer',onOverlay:s=>{const had=!!this.overlayState.previewMove;this.overlayState={...this.overlayState,...s};if(s.previewMove||had)this.renderCanvasPreviewMove();this.renderOverlay();},onPan:({dx,dy})=>{const v=$('#viewport');v.scrollLeft-=dx*this.zoom;v.scrollTop-=dy*this.zoom;this.renderRulers();}});this.interaction.setPanModifier(this.spaceDown);}
 setupCanvas(){this.canvas.addEventListener('pointerdown',e=>this.onPointerDown(e));this.canvas.addEventListener('pointermove',e=>this.onPointerMove(e));this.canvas.addEventListener('pointerup',e=>this.onPointerUp(e));this.canvas.addEventListener('pointercancel',()=>{this.cancelCustomGesture();this.interaction?.cancel();this.renderAll();});this.canvas.addEventListener('contextmenu',e=>this.onContextMenu(e));$('#viewport').addEventListener('scroll',()=>this.renderRulers());$('#viewport').addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();const i=ZOOMS.indexOf(this.zoom),ni=clamp(i+(e.deltaY<0?1:-1),0,ZOOMS.length-1);this.setZoom(ZOOMS[ni]);}},{passive:false});}
 selectionHandleAt(p){const ids=this.state.selection.ids;if(ids.length!==1)return null;const page=this.activePage(),n=M.nodeById(page,ids[0]),tree=new M.TreeModel(page);if(!n||tree.isEffectivelyLocked(n.id))return null;const tol=6/Math.max(.01,this.zoom);if(n.type==='polygon'){for(let i=0;i<n.points.length;i++)if(Math.hypot(n.points[i].x-p.x,n.points[i].y-p.y)<=tol)return{type:'polygon-point',index:i,node:n};}if(n.type==='line'){if(Math.hypot(n.x1-p.x,n.y1-p.y)<=tol)return{type:'line-point',index:0,node:n};if(Math.hypot(n.x2-p.x,n.y2-p.y)<=tol)return{type:'line-point',index:1,node:n};}if(['rectangle','circle','text','image'].includes(n.type)){const b=R.FramebufferRenderer.visualBounds(n.id,{project:this.state.project,pageId:page.id,assets:this.state.assets});for(const [x,y,k] of [[b.x,b.y,'nw'],[b.x+b.w-1,b.y,'ne'],[b.x,b.y+b.h-1,'sw'],[b.x+b.w-1,b.y+b.h-1,'se']])if(Math.hypot(x-p.x,y-p.y)<=tol)return{type:'resize',corner:k,node:n,startBounds:{...b}};}return null;}
 onPointerDown(e){if(e.button===2)return;const p=this.logicalPoint(e),hp=this.logicalPointFloat(e);this.canvas.setPointerCapture?.(e.pointerId);if(this.tool==='pointer'){this.pageSelectedId=null;const handle=e.altKey?null:this.selectionHandleAt(hp);if(handle){this.beginLiveHandle(handle,p);return;}this.updateInteraction();this.interaction.pointerDown({...p,ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey,altKey:e.altKey,button:e.button});this.pageSelectedId=this.state.pageSelectedId??null;this.pageLayers.render();this.properties.render();this.renderOverlay();return;}if(this.tool==='select'){this.pageSelectedId=null;this.updateInteraction();this.interaction.pointerDown({...p,ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey,altKey:false,button:e.button});this.pageSelectedId=this.state.pageSelectedId??null;this.pageLayers.render();this.properties.render();this.renderOverlay();return;}if(this.tool==='pencil'||this.tool==='eraser'){this.beginPaint(p);return;}if(['line','rectangle','circle','polygon','text'].includes(this.tool))this.beginLiveDraw(this.tool,p);}
 onPointerMove(e){const p=this.logicalPoint(e),hp=this.logicalPointFloat(e);$('#cursorStatus').textContent=`x: ${p.x} y: ${p.y}`;if(this.customGesture){const g=this.customGesture;g.last=p;if(g.type==='paint')this.updatePaint(g,p);else if(g.type==='draw-live')this.updateLiveDraw(g,p);else if(g.type==='resize-live')this.updateLiveResize(g,p);else if(g.type==='polygon-point-live'||g.type==='line-point-live')this.updateLivePoint(g,p);return;}if((this.tool==='pointer'||this.tool==='select')&&this.interaction){this.interaction.pointerMove({...p,ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey,altKey:e.altKey});if(this.tool==='pointer'&&this.interaction.mode==='Idle'){if(this.spaceDown)this.canvas.style.cursor='grab';else{const h=this.selectionHandleAt(hp);if(h?.type==='resize')this.canvas.style.cursor=['nw','se'].includes(h.corner)?'nwse-resize':'nesw-resize';else if(h)this.canvas.style.cursor='pointer';else{const hit=new I.HitTest(this.state.project,this.activePage().id,this.state.assets).topmostAt(p.x,p.y,{ignoreLocked:true});this.canvas.style.cursor=hit?'move':'default';}}}else if(this.tool==='select')this.canvas.style.cursor='crosshair';this.renderOverlay();}}
 onPointerUp(e){const p=this.logicalPoint(e);if(this.customGesture){const g=this.customGesture;this.customGesture=null;if(g.type==='paint')this.commitPaint(g);else if(g.type==='draw-live')this.commitLiveDraw(g);else if(g.type==='resize-live'||g.type==='polygon-point-live'||g.type==='line-point-live')this.commitLiveHandle(g);this.overlayState={};this.renderAll();return;}if((this.tool==='pointer'||this.tool==='select')&&this.interaction){this.interaction.pointerUp({...p,ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey,altKey:e.altKey});this.overlayState={};this.renderAll();}}
 cancelCustomGesture(){const g=this.customGesture;if(!g)return;if(g.type==='draw-live'){const page=this.activePage();page.nodes=page.nodes.filter(n=>n.id!==g.nodeId);this.state.selection.replace(g.previousSelection||[]);}else if(g.type==='paint'){if(g.targetKind==='page'){const p=this.activePage();p.overlay=structuredClone(g.originalOverlay);}else{const n=M.nodeById(this.activePage(),g.nodeId);if(n)n.overlay=structuredClone(g.originalOverlay);}}else if(['resize-live','polygon-point-live','line-point-live'].includes(g.type)){const n=M.nodeById(this.activePage(),g.nodeId);if(n)Object.assign(n,structuredClone(g.original));}this.customGesture=null;this.overlayState={};this.renderCanvas();} creationParentId(){const page=this.activePage(),id=this.state.selection.primaryId,tree=new M.TreeModel(page);if(id){if(tree.isEffectivelyLocked(id)){this.notice('当前父图层已锁定，无法创建子元素');return null;}return id;}if(page.locked){this.notice('页面已锁定，无法创建元素');return null;}return page.id;} beginLiveDraw(tool,p){const page=this.activePage(),previousSelection=[...this.state.selection.ids],parentId=this.creationParentId();if(!parentId)return false;let n;if(tool==='line')n=M.createNode('line',{parentId,x1:p.x,y1:p.y,x2:p.x,y2:p.y,lineWidth:1});else if(tool==='rectangle')n=M.createNode('rectangle',{parentId,x:p.x,y:p.y,w:1,h:1,lineWidth:1,fill:{mode:'transparent'}});else if(tool==='circle')n=M.createNode('circle',{parentId,x:p.x,y:p.y,w:1,h:1,lineWidth:1,fill:{mode:'transparent'}});else if(tool==='polygon')n=M.createNode('polygon',{parentId,points:[{x:p.x,y:p.y},{x:p.x,y:p.y},{x:p.x,y:p.y}],lineWidth:1,fill:{mode:'transparent'}});else n=M.createNode('text',{parentId,x:p.x,y:p.y,w:40,h:24,text:'文字',fontSize:16});page.nodes.push(n);this.state.selection.replace([n.id]);this.customGesture={type:'draw-live',tool,nodeId:n.id,start:p,last:p,previousSelection};this.renderCanvas();this.renderOverlay();}
 updateLiveDraw(g,p){const n=M.nodeById(this.activePage(),g.nodeId);if(!n)return;const x=Math.min(g.start.x,p.x),y=Math.min(g.start.y,p.y),w=Math.max(1,Math.abs(p.x-g.start.x)+1),h=Math.max(1,Math.abs(p.y-g.start.y)+1);if(n.type==='line'){n.x1=g.start.x;n.y1=g.start.y;n.x2=p.x;n.y2=p.y;}else if(n.type==='polygon'){n.points=[{x,y:y+h-1},{x:x+Math.floor((w-1)/2),y},{x:x+w-1,y:y+h-1}];}else{n.x=x;n.y=y;n.w=n.type==='text'?Math.max(40,w):w;n.h=n.type==='text'?Math.max(24,h):h;}this.renderCanvas();this.renderOverlay();this.properties.render();}
 commitLiveDraw(g){const page=this.activePage(),n=M.nodeById(page,g.nodeId);if(!n)return false;const final=structuredClone(n);page.nodes=page.nodes.filter(x=>x.id!==g.nodeId);this.state.selection.replace(g.previousSelection||[]);const ok=this.exec(new C.AddNodesCommand([final],page.id,'创建'+final.name));if(ok){this.state.selection.replace([final.id]);this.setTool('pointer');this.renderAll();}return ok;}
 beginLiveHandle(handle,p){const n=handle.node,original=structuredClone(n);const type=handle.type==='resize'?'resize-live':handle.type==='polygon-point'?'polygon-point-live':'line-point-live';this.customGesture={type,nodeId:n.id,index:handle.index,corner:handle.corner,startBounds:handle.startBounds,start:p,last:p,original};}
 updateLiveResize(g,p){const n=M.nodeById(this.activePage(),g.nodeId);if(!n)return;const b=g.startBounds,ax=g.corner.includes('w')?b.x+b.w-1:b.x,ay=g.corner.includes('n')?b.y+b.h-1:b.y;let w=Math.max(1,Math.abs(p.x-ax)+1),h=Math.max(1,Math.abs(p.y-ay)+1);if(n.aspectLocked){const ratio=b.w/Math.max(1,b.h),sx=w/Math.max(1,b.w),sy=h/Math.max(1,b.h);if(sx>=sy)h=Math.max(1,Math.round(w/ratio));else w=Math.max(1,Math.round(h*ratio));}const x=g.corner.includes('w')?ax-w+1:ax,y=g.corner.includes('n')?ay-h+1:ay;n.x=x;n.y=y;n.w=w;n.h=h;this.renderCanvas();this.renderOverlay();this.properties.render();}
 updateLivePoint(g,p){const n=M.nodeById(this.activePage(),g.nodeId);if(!n)return;if(g.type==='polygon-point-live')n.points[g.index]={x:p.x,y:p.y};else if(g.index===0){n.x1=p.x;n.y1=p.y;}else{n.x2=p.x;n.y2=p.y;}this.renderCanvas();this.renderOverlay();this.properties.render();}
 commitLiveHandle(g){const page=this.activePage(),n=M.nodeById(page,g.nodeId);if(!n)return false;let patch;if(g.type==='resize-live')patch={x:n.x,y:n.y,w:n.w,h:n.h};else if(g.type==='polygon-point-live')patch={points:structuredClone(n.points)};else patch={x1:n.x1,y1:n.y1,x2:n.x2,y2:n.y2};Object.assign(n,structuredClone(g.original));return this.exec(new C.UpdateNodesCommand([g.nodeId],patch,page.id,g.type==='resize-live'?'调整大小':'移动控制点'));}
 linePoints(a,b){const pts=[],dx=Math.abs(b.x-a.x),sx=a.x<b.x?1:-1,dy=-Math.abs(b.y-a.y),sy=a.y<b.y?1:-1;let err=dx+dy,x=a.x,y=a.y;while(true){pts.push({x,y});if(x===b.x&&y===b.y)break;const e2=2*err;if(e2>=dy){err+=dy;x+=sx;}if(e2<=dx){err+=dx;y+=sy;}}return pts;}
 paintTarget(){const page=this.activePage(),id=this.state.selection.primaryId,n=M.nodeById(page,id),tree=new M.TreeModel(page);if(n){if(n.type!=='image'||tree.isEffectivelyLocked(n.id)||!tree.isEffectivelyVisible(n.id))return null;return{kind:'node',node:n};}if(!page.locked)return{kind:'page',page};return null;}
 beginPaint(p){const t=this.paintTarget();if(!t){this.notice('铅笔和橡皮擦只能编辑已选择且未锁定的图片 / 栅格图层；未选择普通图层时直接编辑页面背景');return false;}this.notice('');if(t.kind==='page'){this.state.selection.clear();this.pageSelectedId=t.page.id;this.pageLayers?.render();this.properties?.render();}const overlay=t.kind==='page'?t.page.overlay:t.node.overlay,g={type:'paint',targetKind:t.kind,nodeId:t.node?.id||null,pageId:t.page?.id||this.activePage().id,value:this.tool==='pencil'?1:0,start:p,last:p,lastPaint:p,originalOverlay:structuredClone(overlay||{}),changed:false};this.customGesture=g;this.applyPaintSegment(g,p,p);this.renderCanvas();return true;}
 applyPaintSegment(g,a,b){const page=this.activePage();let target,ox=0,oy=0,w=400,h=300;if(g.targetKind==='page'){target=page;}else{target=M.nodeById(page,g.nodeId);if(!target||target.type!=='image')return false;ox=target.x||0;oy=target.y||0;w=target.w;h=target.h;}target.overlay=target.overlay||{};let changed=false;for(const q of this.linePoints(a,b)){const lx=q.x-ox,ly=q.y-oy;if(lx<0||ly<0||lx>=w||ly>=h)continue;const key=`${lx},${ly}`,old=target.overlay[key];if(old!==g.value){target.overlay[key]=g.value;changed=true;}}g.changed=g.changed||changed;return changed;}
 updatePaint(g,p){const from=g.lastPaint||g.start;if(this.applyPaintSegment(g,from,p))this.renderCanvas();g.lastPaint=p;}
 commitPaint(g){const page=this.activePage(),target=g.targetKind==='page'?page:M.nodeById(page,g.nodeId);if(!target)return false;const finalOverlay=structuredClone(target.overlay||{}),before=structuredClone(g.originalOverlay||{});target.overlay=before;if(!g.changed){this.renderCanvas();return false;}return g.targetKind==='page'?this.exec(new C.UpdatePageCommand(page.id,{overlay:finalOverlay},g.value?'背景铅笔':'背景橡皮')):this.exec(new C.UpdateNodesCommand([target.id],{overlay:finalOverlay},page.id,g.value?'铅笔':'橡皮'));}
 setSelectionAxis(axis,target){const page=this.activePage(),tree=new M.TreeModel(page),roots=this.state.selection.transformRoots(tree);this.exec({label:'设置位置',execute:()=>{let changed=false;for(const id of roots){if(tree.isEffectivelyLocked(id))continue;const b=R.FramebufferRenderer.visualBounds(id,{project:this.state.project,pageId:page.id,assets:this.state.assets}),d=Math.round(target-b[axis]);if(d){C.moveNodeTree(page,id,axis==='x'?d:0,axis==='y'?d:0);changed=true;}}return changed;}});}
 setSelectionSize(axis,target){const page=this.activePage(),ids=this.state.selection.ids.filter(id=>['rectangle','circle','text','image'].includes(M.nodeById(page,id)?.type));target=Math.max(1,Math.round(Number(target)));if(!ids.length||!Number.isFinite(target))return false;return this.exec(new C.UpdateNodesCommand(ids,n=>{const ratio=n.w/Math.max(1,n.h);if(axis==='w')return n.aspectLocked?{w:target,h:Math.max(1,Math.round(target/ratio))}:{w:target};return n.aspectLocked?{h:target,w:Math.max(1,Math.round(target*ratio))}:{h:target};},page.id,'调整尺寸'));}
 setPolygonPointCount(id,count){const page=this.activePage(),n=M.nodeById(page,id);if(!n||n.type!=='polygon')return;count=clamp(Math.round(count),3,24);const pts=n.points.map(p=>({...p}));while(pts.length<count){const last=pts.at(-1),prev=pts.at(-2)||last;pts.push({x:last.x+(last.x-prev.x||10),y:last.y+(last.y-prev.y)});}while(pts.length>count)pts.pop();this.exec(new C.UpdateNodesCommand([id],{points:pts},page.id,'顶点数量'));}
 selectionBounds(){const page=this.activePage(),tree=new M.TreeModel(page),roots=this.state.selection.transformRoots(tree),bs=roots.map(id=>R.FramebufferRenderer.visualBounds(id,{project:this.state.project,pageId:page.id,assets:this.state.assets})).filter(b=>b.w&&b.h);if(!bs.length)return null;const x=Math.min(...bs.map(b=>b.x)),y=Math.min(...bs.map(b=>b.y)),rr=Math.max(...bs.map(b=>b.x+b.w)),bb=Math.max(...bs.map(b=>b.y+b.h)),pr=this.overlayState.previewMove;return{x:x+(pr?.dx||0),y:y+(pr?.dy||0),w:rr-x,h:bb-y};}
 selectionRects(){const page=this.activePage(),pr=this.overlayState.previewMove,dx=pr?.dx||0,dy=pr?.dy||0;return this.state.selection.ids.map(id=>R.FramebufferRenderer.visualBounds(id,{project:this.state.project,pageId:page.id,assets:this.state.assets})).filter(b=>b&&b.w>0&&b.h>0).map(b=>({x:b.x+dx,y:b.y+dy,w:b.w,h:b.h}));}
 drawFramebuffer(fb){const im=this.ctx.createImageData(400,300);for(let i=0;i<fb.length;i++){const v=fb[i]?0:255,j=i*4;im.data[j]=im.data[j+1]=im.data[j+2]=v;im.data[j+3]=255;}this.ctx.putImageData(im,0,0);this.lastFramebuffer=fb;}
 renderCanvas(){const page=this.activePage();if(!page)return;this.drawFramebuffer(R.FramebufferRenderer.renderPage(this.state.project,page.id,this.state.assets));}
 renderCanvasPreviewMove(){const page=this.activePage(),pr=this.overlayState.previewMove;if(!page||!pr||(!pr.dx&&!pr.dy)){this.renderCanvas();return;}const tree=new M.TreeModel(page),roots=new M.SelectionSet(pr.ids||this.state.selection.ids).transformRoots(tree);for(const id of roots)C.moveNodeTree(page,id,pr.dx,pr.dy,tree);try{this.drawFramebuffer(R.FramebufferRenderer.renderPage(this.state.project,page.id,this.state.assets));}finally{for(const id of roots)C.moveNodeTree(page,id,-pr.dx,-pr.dy,tree);}}
 renderOverlay(){const svg=this.overlay;if(!svg)return;const page=this.activePage(),rects=this.selectionRects(),dx=this.overlayState.previewMove?.dx||0,dy=this.overlayState.previewMove?.dy||0;let html=R.OverlayRenderer.markup({selectionRects:rects,smartGuides:this.overlayState.smartGuides||[],marquee:this.overlayState.marquee});if(rects.length===1){const b=rects[0],size=7/Math.max(.01,this.zoom),half=size/2;for(const [x,y] of [[b.x,b.y],[b.x+b.w-1,b.y],[b.x,b.y+b.h-1],[b.x+b.w-1,b.y+b.h-1]])html+=`<rect class="selection-handle" x="${x-half}" y="${y-half}" width="${size}" height="${size}"/>`;const n=M.nodeById(page,this.state.selection.primaryId);if(n?.type==='polygon')for(const p of n.points)html+=`<rect class="selection-handle" x="${p.x+dx-half}" y="${p.y+dy-half}" width="${size}" height="${size}"/>`;if(n?.type==='line')for(const p of [{x:n.x1,y:n.y1},{x:n.x2,y:n.y2}])html+=`<rect class="selection-handle" x="${p.x+dx-half}" y="${p.y+dy-half}" width="${size}" height="${size}"/>`;}svg.innerHTML=html;}
 renderRulers(){const top=$('#topRuler'),left=$('#leftRuler');if(!top||!left||!this.canvas)return;const dpr=Math.max(1,globalThis.devicePixelRatio||1);for(const c of [top,left]){const r=c.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;}const tr=top.getBoundingClientRect(),lr=left.getBoundingClientRect(),sr=this.canvas.getBoundingClientRect(),tx=top.getContext('2d'),lx=left.getContext('2d');for(const [ctx,canvas] of [[tx,top],[lx,left]]){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);ctx.fillStyle='#242424';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);ctx.strokeStyle='#666';ctx.fillStyle='#bbb';ctx.lineWidth=1;ctx.font='11px system-ui,sans-serif';ctx.textBaseline='top';}const x0=sr.left-tr.left,y0=sr.top-lr.top,bandX0=x0-16,bandX1=x0+400*this.zoom+16,bandY0=y0-16,bandY1=y0+300*this.zoom+16;tx.fillStyle='#2d2d2d';tx.fillRect(bandX0,0,bandX1-bandX0,top.clientHeight);lx.fillStyle='#2d2d2d';lx.fillRect(0,bandY0,left.clientWidth,bandY1-bandY0);const minLabel=44,raw=Math.ceil(minLabel/this.zoom),steps=[1,2,5,10,20,50,100,200],step=steps.find(v=>v>=raw)||200;tx.fillStyle=lx.fillStyle='#bbb';for(let x=0;x<=400;x+=step){const px=x0+x*this.zoom+.5;tx.beginPath();tx.moveTo(px,top.clientHeight-9);tx.lineTo(px,top.clientHeight);tx.stroke();tx.fillText(String(x),px+3,3);}for(let y=0;y<=300;y+=step){const py=y0+y*this.zoom+.5;lx.beginPath();lx.moveTo(left.clientWidth-9,py);lx.lineTo(left.clientWidth,py);lx.stroke();lx.save();lx.translate(3,py+2);lx.rotate(-Math.PI/2);lx.fillText(String(y),0,0);lx.restore();}}
 renderAll(opts={}){const o={canvas:true,properties:true,layers:true,history:true,...opts};if(o.canvas)this.renderCanvas();this.renderOverlay();this.renderRulers();if(o.layers)this.pageLayers?.render();if(o.properties)this.properties?.render();if(o.history)this.history?.render();this.updateInteraction();this.applyLayout();$('#statusText').textContent='400×300 · 1-bit · V17';$('#selectionStatus').textContent=this.state.selection.ids.length?`已选择 ${this.state.selection.ids.length}`:(this.pageSelectedId===this.activePage().id?'已选择页面 / 背景':'未选择');document.title=`400×300 黑白像素编辑器 V17${this.state.dirty?' *':''}`;}
 align(mode){if(this.state.selection.ids.length>=2)this.exec(new C.AlignCommand(mode,this.state.selection.ids,this.state.assets,this.activePage().id));}
 distribute(axis){if(this.state.selection.ids.length>=3)this.exec(new C.DistributeCommand(axis,this.state.selection.ids,this.state.assets,this.activePage().id));}
 setupKeyboard(){window.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey,editing=['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName)||e.target?.isContentEditable;if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();this.saveProject();return;}if(editing)return;if(e.code==='Space'){this.spaceDown=true;this.interaction?.setPanModifier(true);e.preventDefault();return;}if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey?this.bus.redo():this.bus.undo()){this.state.selection.clear();this.renderAll();}return;}if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();if(this.bus.redo()){this.state.selection.clear();this.renderAll();}return;}if(mod&&e.key.toLowerCase()==='c'){e.preventDefault();this.clipboard.copy(this.state.project,this.activePage().id,this.state.selection);return;}if(mod&&e.key.toLowerCase()==='v'){const n=this.clipboard.nextPaste();if(n){e.preventDefault();this.exec(new C.PasteCommand(n.payload,n.offsetIndex,this.activePage().id));}return;}if(mod&&e.key.toLowerCase()==='d'){e.preventDefault();this.exec(new C.DuplicateCommand(this.state.selection.ids,this.activePage().id));return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&this.state.selection.ids.length){e.preventDefault();const step=e.shiftKey?10:1,dx=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,dy=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0,key=`nudge:${e.key}:${e.shiftKey}:${[...this.state.selection.ids].sort().join(',')}`;this.exec(new C.MoveSelectionCommand(this.state.selection.ids,dx,dy,this.activePage().id,{mergeKey:key}));return;}if(['Delete','Backspace'].includes(e.key)&&this.state.selection.ids.length){e.preventDefault();this.exec(new C.DeleteNodesCommand(this.state.selection.ids,this.activePage().id));this.state.selection.clear();this.renderAll();return;}const map={v:'pointer',m:'select',p:'pencil',e:'eraser',l:'line',r:'rectangle',o:'circle',g:'polygon',t:'text',i:'image'},k=e.key.toLowerCase();if(map[k]){e.preventDefault();this.setTool(map[k]);return;}if(e.key==='+'||e.key==='='){const i=ZOOMS.indexOf(this.zoom);this.setZoom(ZOOMS[Math.min(ZOOMS.length-1,i+1)]);}else if(e.key==='-'){const i=ZOOMS.indexOf(this.zoom);this.setZoom(ZOOMS[Math.max(0,i-1)]);}});window.addEventListener('keyup',e=>{if(e.code==='Space'){this.spaceDown=false;this.interaction?.setPanModifier(false);}});}
 setupFiles(){$('#fileImage').onchange=async e=>{const f=e.target.files?.[0];if(f)try{await this.importImageFile(f);}catch(err){alert('导入失败：'+err.message);}e.target.value='';};$('#fileFont').onchange=async e=>{const fs=[...(e.target.files||[])];if(fs.length)try{const r=await this.importFonts(fs);this.notice(`已导入 ${r.imported} 个字体，跳过 ${r.skipped} 个重复字体`);}catch(err){alert('字体导入失败：'+err.message);}e.target.value='';};$('#fileProject').onchange=async e=>{const f=e.target.files?.[0];if(f)try{const out=P.ProjectSerializer.deserialize(await f.text());this.state.project=out.project;this.state.assets=out.assets;this.state.projectFileHandle=null;this.state.projectFileName=f.name;this.state.selection.clear();this.pageSelectedId=this.state.project.activePageId;this.bus=new C.CommandBus(this.state,{limit:100});this.state.dirty=false;await this.hydrateAssets();this.autosave?.clear();this.applyLayout();this.renderAll();}catch(err){alert('项目无效：'+err.message);}e.target.value='';};window.addEventListener('paste',async e=>{if(['INPUT','TEXTAREA'].includes(e.target?.tagName))return;const text=e.clipboardData?.getData('text/plain')||'';if(/<svg[\s\S]*<\/svg>/i.test(text)){e.preventDefault();await this.importSvgText(text);}else if(/#define\s+\w+_width/i.test(text)&&/#define\s+\w+_height/i.test(text)){e.preventDefault();await this.importXbmText(text);}});}
 async chooseReplacementImage(targetId){const page=this.activePage(),target=M.nodeById(page,targetId);if(!target||target.type!=='image'||new M.TreeModel(page).isEffectivelyLocked(targetId))return false;const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,.xbm,image/svg+xml';input.style.display='none';document.body.appendChild(input);input.addEventListener('change',async()=>{const f=input.files?.[0];try{if(f)await this.importImageFile(f,{replaceTargetId:targetId});}catch(err){alert('替换图片失败：'+err.message);}finally{input.remove();}},{once:true});input.addEventListener('cancel',()=>input.remove(),{once:true});input.click();return true;}
 async importImageFile(file,{replaceTargetId=null}={}){if(file.name.toLowerCase().endsWith('.xbm'))return this.importXbmText(await file.text(),file.name,{replaceTargetId});if(file.type==='image/svg+xml'||file.name.toLowerCase().endsWith('.svg'))return this.importSvgText(await file.text(),file.name,{replaceTargetId});const url=await dataUrlFromFile(file),runtime=await decodeImage(url);return this.addImageAsset(url,runtime,file.name,file.type||'image',{sourceType:'bitmap',replaceTargetId});}
 async importSvgText(text,name='svg',{replaceTargetId=null}={}){const meta=parseSvgMeta(text),url='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(text),runtime=await decodeImage(url,meta.width,meta.height);return this.addImageAsset(url,runtime,name,'image/svg+xml',{sourceType:'svg',svgViewBox:meta.viewBox,replaceTargetId});}
 async importXbmText(text,name='xbm',{replaceTargetId=null}={}){const x=parseXbmText(text),c=xbmToCanvas(x),url=c.toDataURL('image/png'),runtime={width:x.width,height:x.height,data:c.getContext('2d').getImageData(0,0,x.width,x.height).data};return this.addImageAsset(url,runtime,name,'image/xbm',{sourceType:'xbm',replaceTargetId});}
 addImageAsset(url,runtime,name,mime,meta={}){const id=this.state.assets.add('image',url,{name,mime});this.state.assets.setRuntime(id,runtime);const targetId=meta.replaceTargetId;if(targetId){const page=this.activePage(),old=M.nodeById(page,targetId),tree=new M.TreeModel(page);if(old?.type==='image'&&!tree.isEffectivelyLocked(targetId)){const ok=this.exec(new C.UpdateNodesCommand([targetId],{assetId:id,sourceWidth:runtime.width,sourceHeight:runtime.height,sourceName:name,sourceType:meta.sourceType||'bitmap',svgViewBox:meta.svgViewBox||null,image:{...(old.image||{}),cropX:0,cropY:0,cropW:runtime.width,cropH:runtime.height}},page.id,'替换图片'));if(ok){this.state.selection.replace([targetId]);this.setTool('pointer');return M.nodeById(page,targetId);}}this.state.assets.delete(id);return null;}const parentId=this.creationParentId();if(!parentId){this.state.assets.delete(id);return null;}const scale=Math.min(1,400/runtime.width,300/runtime.height),w=Math.max(1,Math.round(runtime.width*scale)),h=Math.max(1,Math.round(runtime.height*scale)),n=M.createNode('image',{parentId,x:Math.floor((400-w)/2),y:Math.floor((300-h)/2),w,h,assetId:id,sourceWidth:runtime.width,sourceHeight:runtime.height,sourceName:name,sourceType:meta.sourceType||'bitmap',svgViewBox:meta.svgViewBox||null});this.exec(new C.AddNodesCommand([n],this.activePage().id,'导入图片'));this.state.selection.replace([n.id]);this.setTool('pointer');this.renderAll();return n;}
 async importFonts(files){const recs=[];let skipped=0;for(const f of files){const bytes=new Uint8Array(await f.arrayBuffer()),sha256=await M.sha256Bytes(bytes),existingAsset=this.state.assets.findBySha256('font',sha256),existingFont=(this.state.project.fonts||[]).find(x=>x.sha256===sha256||x.assetId===existingAsset?.id);if(existingFont){skipped++;continue;}let assetId=existingAsset?.id;if(!assetId){const dataUrl=await dataUrlFromFile(new Blob([bytes],{type:f.type||'font/ttf'}));assetId=this.state.assets.add('font',dataUrl,{name:f.name,mime:f.type||'font/ttf',sha256});}const family='Imported_'+sha256.slice(0,16),fixedSize=inferFixedFontSize(f.name),rec={name:f.name,family,fixedSize,assetId,sha256};await this.registerFont(rec).catch(()=>{});recs.push(rec);}if(recs.length)this.exec({label:'导入字体',execute:s=>{s.project.fonts.push(...recs);return true;}});return{imported:recs.length,skipped};}
 async registerFont(rec){if(typeof FontFace==='undefined'||!rec.assetId)return;const key=`${rec.assetId}:${rec.family}`;if(this.fontFaceCache.has(key))return this.fontFaceCache.get(key);const a=this.state.assets.get(rec.assetId);if(!a)return;const ff=new FontFace(rec.family,`url(${a.dataUrl})`),loaded=await ff.load();document.fonts.add(loaded);this.fontFaceCache.set(key,loaded);return loaded;}
 async hydrateAssets(){for(const f of this.state.project.fonts||[])await this.registerFont(f).catch(()=>{});for(const rec of this.state.assets.records())if(rec.type==='image'&&!this.state.assets.getRuntime(rec.id))try{this.state.assets.setRuntime(rec.id,await decodeImage(rec.dataUrl));}catch{}}
 exportPng(){const fb=R.FramebufferRenderer.renderPage(this.state.project,this.activePage().id,this.state.assets),c=document.createElement('canvas');c.width=400;c.height=300;const x=c.getContext('2d'),im=x.createImageData(400,300);for(let i=0;i<fb.length;i++){const v=fb[i]?0:255,j=i*4;im.data[j]=im.data[j+1]=im.data[j+2]=v;im.data[j+3]=255;}x.putImageData(im,0,0);c.toBlob(b=>downloadBlob(b,'screen-400x300.png'),'image/png');return c;}
 async saveProject(){if(typeof window.showSaveFilePicker==='function')try{this.files=new P.ProjectFiles(this.state);await this.files.save();this.autosave?.clear();this.renderAll({canvas:false});return;}catch(err){if(err?.name==='AbortError')return;alert('保存失败：'+err.message);return;}const raw=P.ProjectSerializer.serialize(this.state.project,this.state.assets),name=this.state.projectFileName?.endsWith('.pix')?this.state.projectFileName:'pixel-project-v17.pix';downloadBlob(new Blob([raw],{type:'application/json'}),name);this.state.projectFileName=name;this.state.dirty=false;this.autosave?.clear();this.renderAll({canvas:false});}
 async openProject(){if(typeof window.showOpenFilePicker==='function')try{this.files=new P.ProjectFiles(this.state);await this.files.open();this.state.selection.clear();this.pageSelectedId=this.state.project.activePageId;this.bus=new C.CommandBus(this.state,{limit:100});await this.hydrateAssets();this.autosave?.clear();this.applyLayout();this.renderAll();return;}catch(err){if(err?.name==='AbortError')return;alert('打开失败：'+err.message);return;}$('#fileProject').click();}
 setupDockSplitters(){const l=()=>this.state.project.workspaceLayout;const width=(id,key,dir)=>{const el=$(id);let active=false,startX=0,start=0;el.onpointerdown=e=>{active=true;startX=e.clientX;start=l()[key];el.setPointerCapture?.(e.pointerId);};el.onpointermove=e=>{if(!active)return;l()[key]=clamp(Math.round(start+(e.clientX-startX)*dir),170,520);this.state.dirty=true;this.applyLayout();this.renderRulers();};el.onpointerup=()=>active=false;};width('#leftWidthSplitter','leftWidth',1);width('#rightWidthSplitter','rightWidth',-1);const split=(id,key,container)=>{const el=$(id);let active=false;el.onpointerdown=e=>{active=true;el.setPointerCapture?.(e.pointerId);};el.onpointermove=e=>{if(!active)return;const r=$(container).getBoundingClientRect(),min=Math.min(.45,120/Math.max(1,r.height));l()[key]=clamp((e.clientY-r.top)/Math.max(1,r.height),min,1-min);this.state.dirty=true;this.applyLayout();this.renderRulers();};el.onpointerup=()=>active=false;};split('#leftPaneSplitter','leftSplit','#leftSidebar');split('#rightPaneSplitter','rightSplit','#rightSidebar');}
 applyLayout(){const l=this.state.project.workspaceLayout||M.defaultWorkspaceLayout();this.state.project.workspaceLayout=l;document.documentElement.style.setProperty('--left-w',(l.leftWidth||260)+'px');document.documentElement.style.setProperty('--right-w',(l.rightWidth||320)+'px');$('#leftTopPane').style.flex=`${l.leftSplit??.5} 1 0`;$('#leftBottomPane').style.flex=`${1-(l.leftSplit??.5)} 1 0`;$('#rightTopPane').style.flex=`${l.rightSplit??.5} 1 0`;$('#rightBottomPane').style.flex=`${1-(l.rightSplit??.5)} 1 0`;}
 setupRulers(){window.addEventListener('resize',()=>{this.applyLayout();this.renderRulers();});}
 onContextMenu(e){e.preventDefault();const p=this.logicalPoint(e),hit=new I.HitTest(this.state.project,this.activePage().id,this.state.assets).topmostAt(p.x,p.y,{ignoreLocked:false});if(!hit)return;this.state.selection.replace([hit.id]);this.renderAll({canvas:false,history:false});const m=$('#contextMenu');m.dataset.nodeId=hit.id;m.style.left=e.clientX+'px';m.style.top=e.clientY+'px';m.classList.add('open');}
 setupContextMenu(){document.addEventListener('pointerdown',e=>{if(!e.target.closest('#contextMenu')&&e.button!==2)$('#contextMenu').classList.remove('open');});document.querySelectorAll('#contextMenu [data-context]').forEach(b=>b.onclick=async()=>{const act=b.dataset.context;$('#contextMenu').classList.remove('open');if(act==='duplicate')this.exec(new C.DuplicateCommand(this.state.selection.ids,this.activePage().id));else if(act==='delete'){this.exec(new C.DeleteNodesCommand(this.state.selection.ids,this.activePage().id));this.state.selection.clear();this.renderAll();}else if(act==='rasterize')await this.rasterizeSelected();else if(act==='save-image')await this.saveSelectedImage();else if(act==='copy-image')await this.copySelectedImage();});}
 subtreeIds(id){const t=new M.TreeModel(this.activePage()),s=new Set();const add=x=>{s.add(x);for(const c of t.childrenOf(x))add(c.id);};add(id);return s;}
 subtreeAsset(id){const page=this.activePage(),cut=R.FramebufferRenderer.subtreeRgba(this.state.project,page.id,id,this.state.assets),c=document.createElement('canvas');c.width=cut.w;c.height=cut.h;const x=c.getContext('2d'),im=x.createImageData(cut.w,cut.h);im.data.set(cut.data);x.putImageData(im,0,0);return{...cut,canvas:c};}
 async rasterizeSelected(){const id=this.state.selection.primaryId,n=M.nodeById(this.activePage(),id),tree=new M.TreeModel(this.activePage());if(!n||tree.isEffectivelyLocked(id)||(n.type==='image'&&tree.childrenOf(id).length===0))return false;if(typeof confirm==='function'&&!confirm('确认将该图层及其所有子图层栅格化为一个图片图层吗？'))return false;const page=this.activePage(),a=this.subtreeAsset(id),url=a.canvas.toDataURL('image/png'),assetId=this.state.assets.add('image',url,{name:n.name+'.png',mime:'image/png'});this.state.assets.setRuntime(assetId,{width:a.w,height:a.h,data:a.data});const ids=this.subtreeIds(id),idx=page.nodes.findIndex(x=>x.id===id),replacement=M.createNode('image',{id:n.id,parentId:n.parentId,name:n.name,visible:n.visible,locked:n.locked,x:a.x,y:a.y,w:a.w,h:a.h,assetId,sourceWidth:a.w,sourceHeight:a.h,sourceName:n.name+'.png'});this.exec({label:'栅格化图层',execute:()=>{page.nodes=page.nodes.filter(x=>!ids.has(x.id));page.nodes.splice(Math.min(idx,page.nodes.length),0,replacement);this.state.selection.replace([replacement.id]);return true;}});return true;}
 async saveSelectedImage(){const id=this.state.selection.primaryId;if(!id)return;const a=this.subtreeAsset(id);a.canvas.toBlob(b=>downloadBlob(b,(M.nodeById(this.activePage(),id)?.name||'element')+'.png'),'image/png');}
 async copySelectedImage(){const id=this.state.selection.primaryId;if(!id)return false;try{const a=this.subtreeAsset(id),blob=await new Promise(r=>a.canvas.toBlob(r,'image/png'));if(!blob)throw new Error('无法生成图片');if(!navigator.clipboard?.write||!globalThis.ClipboardItem){this.notice('当前浏览器不支持复制图片到系统剪贴板');return false;}await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);this.notice('图片已复制到剪贴板');return true;}catch(err){this.notice('复制图片失败：'+(err?.message||err));return false;}}
 notice(text){const n=$('#noticeText');if(n)n.textContent=text;}
 countType(t){return this.activePage().nodes.filter(n=>n.type===t).length;}
 testApi(){return{version:17,editor:this,getZoom:()=>this.zoom,getTool:()=>this.tool,getSelectionIds:()=>[...this.state.selection.ids],getSelectionRects:()=>this.selectionRects().map(x=>({...x})),getNode:id=>structuredClone(M.nodeById(this.activePage(),id)),getNodePositions:()=>Object.fromEntries(this.activePage().nodes.map(n=>[n.id,{x:n.x??n.x1??0,y:n.y??n.y1??0}])),historyCount:()=>this.bus.entries.length,countType:t=>this.countType(t),getActivePage:()=>structuredClone(this.activePage()),getState:()=>this.state,validateHierarchy:()=>new M.TreeModel(this.activePage()).validateHierarchy(),serialize:()=>P.ProjectSerializer.serialize(this.state.project,this.state.assets),pixFileType:()=>P.PIX_FILE_TYPE,framebufferString:()=>Array.from(R.FramebufferRenderer.renderPage(this.state.project,this.activePage().id,this.state.assets)).join(''),previewFramebufferBlackCount:()=>this.lastFramebuffer.reduce((a,b)=>a+b,0),isPixelGridVisible:()=>this.overlay.classList.contains('pixel-grid'),createNode:(type,props={})=>{const n=M.createNode(type,{...props,parentId:props.parentId??this.activePage().id});this.exec(new C.AddNodesCommand([n],this.activePage().id));this.state.selection.replace([n.id]);this.pageSelectedId=null;this.renderAll();return n.id;}};}
}
U.Workspace=Workspace;
})();
