import './namespace.js';
import './model-bridge.js';
import './rendering-bridge.js';
import './command-bridge.js';
import './persistence-bridge.js';
import './interaction-bridge.js';
import './ui-bridge.js';
import '../ui/properties.js';
import '../app/workspace.js';
