import { installElementClipboardRuntime } from './clipboard/element-clipboard.js';
import { installFontImportRuntime } from './fonts/font-import.js';
import { installFontManagerRuntime } from './fonts/font-manager.js';
import { installFontOptionsRuntime } from './fonts/font-options.js';
import { installCommandCoalescingRuntime } from './history/command-coalescing.js';
import { installEditBoundariesRuntime } from './media/edit-boundaries.js';
import { installImageRuntime } from './media/image-runtime.js';
import { installRasterLayerRuntime } from './media/raster-layer.js';
import { installRasterSizingRuntime } from './media/raster-sizing.js';
import { installV17SchemaRuntime } from './model/v17-schema.js';
import { installEditorPreferencesRuntime } from './preferences/editor-preferences.js';
import { installPageFillPropertiesRuntime } from './properties/page-fill-properties.js';
import { installShapeStylePropertiesRuntime } from './properties/shape-style-properties.js';
import { installTextContentEditingRuntime } from './properties/text-content-editing.js';
import { installTextFontActionsRuntime } from './properties/text-font-actions.js';
import { installPaintBrushRuntime } from './raster/paint-brush.js';
import { installTriStateRasterRuntime } from './raster/tristate-raster.js';
import { installBinaryImagePreviewRuntime } from './rendering/binary-image-preview.js';
import { installBinaryImageRuntime } from './rendering/binary-image.js';
import { installHierarchyClippingRuntime } from './rendering/hierarchy-clipping.js';
import { installPixelStrokeRuntime } from './rendering/pixel-stroke.js';
import { installSelectionOverlayRuntime } from './rendering/selection-overlay.js';
import { installStrokeStyleRuntime } from './rendering/stroke-style.js';
import { installTextLayoutRuntime } from './rendering/text-layout.js';
import { installTransparencyOverlayRuntime } from './rendering/transparency-overlay.js';
import { installSelectionGeometryRuntime } from './selection/selection-geometry.js';
import { installToolOptionsRuntime } from './tools/tool-options-bar.js';
import { installToolStateRuntime } from './tools/tool-state.js';
import { installTextToolOptionsRuntime } from './tools/text-tool-options.js';
import { installSelectionTransformRuntime } from './transforms/selection-transform.js';
import { installTransformModelRuntime } from './transforms/transform-model.js';
import { installContextMenuRuntime } from './ui/context-menu.js';
import { installContextMenuBoundaryRuntime } from './ui/context-menu-boundary.js';
import { installHistoryPropertiesRuntime } from './ui/history-properties.js';

function installRuntimeModules() {
  installV17SchemaRuntime(globalThis);
  installEditorPreferencesRuntime(globalThis);
  installCommandCoalescingRuntime(globalThis);
  installFontOptionsRuntime(globalThis);
  installToolStateRuntime(globalThis);
  installTextToolOptionsRuntime(globalThis);
  installToolOptionsRuntime(globalThis);
  installImageRuntime(globalThis);
  installBinaryImageRuntime(globalThis);
  installBinaryImagePreviewRuntime(globalThis);
  installPixelStrokeRuntime(globalThis);
  installHierarchyClippingRuntime(globalThis);
  installStrokeStyleRuntime(globalThis);
  installShapeStylePropertiesRuntime(globalThis);
  installPageFillPropertiesRuntime(globalThis);
  installTriStateRasterRuntime(globalThis);
  installRasterLayerRuntime(globalThis);
  installPaintBrushRuntime(globalThis);
  installRasterSizingRuntime(globalThis);
  installEditBoundariesRuntime(globalThis);
  installTransformModelRuntime(globalThis);
  installSelectionGeometryRuntime(globalThis);
  installSelectionTransformRuntime(globalThis);
  installElementClipboardRuntime(globalThis);
  installContextMenuRuntime(globalThis);
  installContextMenuBoundaryRuntime(globalThis);
  installHistoryPropertiesRuntime(globalThis);
  installSelectionOverlayRuntime(globalThis);
  installTransparencyOverlayRuntime(globalThis);
  installTextLayoutRuntime(globalThis);
  installFontManagerRuntime(globalThis);
  installTextFontActionsRuntime(globalThis);
  installTextContentEditingRuntime(globalThis);
  installFontImportRuntime(globalThis);
}

installRuntimeModules();

export { installRuntimeModules };
