import './core/index.js';
import { bootstrapPixelEdit } from './app/bootstrap.js';
import { installElementClipboardRuntime } from './clipboard/element-clipboard.js';
import { installFontImportRuntime } from './fonts/font-import.js';
import { installFontManagerRuntime } from './fonts/font-manager.js';
import { installFontOptionsRuntime } from './fonts/font-options.js';
import { installEditBoundariesRuntime } from './media/edit-boundaries.js';
import { installImageRuntime } from './media/image-runtime.js';
import { installRasterLayerRuntime } from './media/raster-layer.js';
import { installRasterSizingRuntime } from './media/raster-sizing.js';
import { installEditorPreferencesRuntime } from './preferences/editor-preferences.js';
import { installPropertySystem } from './properties/property-system.js';
import { installFloodFillRuntime } from './raster/flood-fill.js';
import { installPaintBrushRuntime } from './raster/paint-brush.js';
import { installTriStateRasterRuntime } from './raster/tristate-raster.js';
import { installBinaryImagePreviewRuntime } from './rendering/binary-image-preview.js';
import { installBinaryImageRuntime } from './rendering/binary-image.js';
import { installPixelStrokeRuntime } from './rendering/pixel-stroke.js';
import { installSelectionOverlayRuntime } from './rendering/selection-overlay.js';
import { installTextLayoutRuntime } from './rendering/text-layout.js';
import { installTransparencyOverlayRuntime } from './rendering/transparency-overlay.js';
import { installSelectionGeometryRuntime } from './selection/selection-geometry.js';
import { installCanvasCursorRuntime } from './tools/canvas-cursor.js';
import { installFillToolOptionsRuntime } from './tools/fill-tool-options.js';
import { installToolOptionsRuntime } from './tools/tool-options-bar.js';
import { installToolStateRuntime } from './tools/tool-state.js';
import { installToolSystemRuntime } from './tools/tool-controller.js';
import { installTextToolOptionsRuntime } from './tools/text-tool-options.js';
import { installPhotopeaTransformUIRuntime } from './transforms/photopea-transform-ui.js';
import { installSelectionTransformRuntime } from './transforms/selection-transform.js';
import { installContextMenuRuntime } from './ui/context-menu.js';
import { installContextMenuBoundaryRuntime } from './ui/context-menu-boundary.js';
import { installHistoryPropertiesRuntime } from './ui/history-properties.js';

function installRuntimeModules() {
  installEditorPreferencesRuntime(globalThis);
  installFontOptionsRuntime(globalThis);
  installToolStateRuntime(globalThis);
  installTextToolOptionsRuntime(globalThis);
  installToolOptionsRuntime(globalThis);
  installFillToolOptionsRuntime(globalThis);
  installImageRuntime(globalThis);
  installBinaryImageRuntime(globalThis);
  installPixelStrokeRuntime(globalThis);
  installTriStateRasterRuntime(globalThis);
  installRasterLayerRuntime(globalThis);
  installPaintBrushRuntime(globalThis);
  installRasterSizingRuntime(globalThis);
  installEditBoundariesRuntime(globalThis);
  installSelectionGeometryRuntime(globalThis);
  installSelectionTransformRuntime(globalThis);
  installFloodFillRuntime(globalThis);
  installElementClipboardRuntime(globalThis);
  installContextMenuRuntime(globalThis);
  installContextMenuBoundaryRuntime(globalThis);
  installHistoryPropertiesRuntime(globalThis);
  installSelectionOverlayRuntime(globalThis);
  installPhotopeaTransformUIRuntime(globalThis);
  installTransparencyOverlayRuntime(globalThis);
  installCanvasCursorRuntime(globalThis);
  installTextLayoutRuntime(globalThis);
  installFontManagerRuntime(globalThis);
  installFontImportRuntime(globalThis);
  installPropertySystem(globalThis);
  installBinaryImagePreviewRuntime(globalThis);
  installToolSystemRuntime(globalThis);
}

installRuntimeModules();
bootstrapPixelEdit(globalThis);

export { installRuntimeModules };
